name: bnidark
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.1
  get_storage: ^2.0.3


  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.10
  cloud_firestore_web: ^2.6.10
  firebase_auth: ^3.3.11
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  material_design_icons_flutter: ^5.0.6595
  location: ^4.3.0
  url_launcher: ^6.0.20
  firebase_dart: ^1.0.5 
  dropdown_button2: ^1.4.0
  multiselect: ^0.0.4

# flutter_localizations:
#   sdk:flutter
#   provider:^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  firebase_core: ^1.13.1

flutter:


  uses-material-design: true

  assets:
    - assets/
    


